version: "3"

# All available services
services:

  postgres-datawarehouse:
    container_name: "postgres-datawarehouse"
    restart: "no"
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - C:/Users/tt200/docker/volumes/postgres-datawarehouse:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pgadmin4:
    container_name: "pgadmin4"
    restart: "no"
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - 5050:80

      
  postgres:
    container_name: "postgres-metabase"
    restart: "no"
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=admin'
      - 'METABASE_PASSOWRD=metabase'
    volumes:
      - C:/Users/tt200/docker/volumes/postgres-metabase:/var/lib/postgresql/data/
      - C:/Users/tt200/Desktop/Git/Stack-Metabase/services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

  metabase:
    container_name: "metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - C:/Users/tt200/Desktop/Git/Stack-Metabase/config/metabase_database.env
    ports:
      - 3000:3000

# Volumes to persist data
volumes:
  postgres_volume: