version: "3"

services:

  postgres-datawarehouse:
    container_name: "postgres-datawarehouse"
    restart: "no"
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - /home/tre-rn/docker/postgres-datawarehouse:/var/lib/postgresql/data/
    ports:
      - 5434:5432

  pgadmin4:
    container_name: "pgadmin4"
    restart: "no"
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - 5050:80

  postgres-metabase:
    container_name: "postgres-metabase"
    restart: "no"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - /home/tre-rn/docker/volumes/postgres-metabase:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  metabase:
    container_name: "metabase"
    restart: "always"
    image: metabase/metabase
    links:
      - "postgres-metabase:database"
    env_file:
      - ./config/metabase_database.env
    ports:
      - 3000:3000
